[project]
name = "cs168-things"
version = "0.1.0"
description = "prokects for cs168"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]

[dependency-groups]
dev = [
    "black>=26.1.0",
]
